In [ ]:
%pip install pymysql | grep -v 'already satisfied'
%pip install -U -q PyDrive

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pymysql
  Downloading PyMySQL-1.0.2-py3-none-any.whl (43 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.0.2

In [ ]:
from sqlalchemy import create_engine
from sqlalchemy import exc

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

import requests
import pymysql
from io import StringIO

import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [ ]:
# auth current session user & get google drive access
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [ ]:
## Full Census Data - TRANSFORMED ALL YEARS
# https://drive.google.com/file/d/1UH8j8FFkQAVx7f0BXJWkhILi0_lViguc/view?usp=sharing
fileDownloaded = drive.CreateFile({'id':'1UH8j8FFkQAVx7f0BXJWkhILi0_lViguc'})
fileDownloaded.GetContentFile('full_census_enriched.csv')

census_final = pd.read_csv('full_census_enriched.csv', delimiter=',', encoding='utf-8', low_memory=False, na_values='NaN')

# import to db
engine = create_engine("mysql+pymysql://admin:cse6242110@cse6242.czj7hqwhnoml.us-east-1.rds.amazonaws.com/realestate", echo=True)
census_final.to_sql('census_final', con=engine, if_exists='replace', index = False, chunksize = 10000)

In [ ]:
## Full Census Data - TRANSFORMED 2020 ONLY
# https://drive.google.com/file/d/1MK4pXlmSbzS1yF61QE5tb7w9o8AESJir/view?usp=sharing
fileDownloaded = drive.CreateFile({'id':'1MK4pXlmSbzS1yF61QE5tb7w9o8AESJir'})
fileDownloaded.GetContentFile('full_census_enriched_2020.csv')

census_final_2020 = pd.read_csv('full_census_enriched_2020.csv', delimiter=',', encoding='utf-8', low_memory=False, na_values='NaN')

# import to db
engine = create_engine("mysql+pymysql://admin:cse6242110@cse6242.czj7hqwhnoml.us-east-1.rds.amazonaws.com/realestate", echo=True)
census_final_2020.to_sql('census_final_2020', con=engine, if_exists='replace', index = False, chunksize = 10000)

In [ ]:
## Yelp - TRANSFORMED
# https://drive.google.com/file/d/1VVD2UwMqVW18VoETK1zh5TSDB8sY_0bv/view?usp=sharing
fileDownloaded = drive.CreateFile({'id':'1VVD2UwMqVW18VoETK1zh5TSDB8sY_0bv'})
fileDownloaded.GetContentFile('yelp_enriched.csv')

yelp_enriched = pd.read_csv('yelp_enriched.csv', delimiter=',', encoding='utf-8', low_memory=False, na_values='NaN')

# import to db
engine = create_engine("mysql+pymysql://admin:cse6242110@cse6242.czj7hqwhnoml.us-east-1.rds.amazonaws.com/realestate", echo=True)
yelp_enriched.to_sql('yelp_enriched', con=engine, if_exists='replace', index = False, chunksize = 10000)

In [ ]:
## Accessibility - TRANSFORMED
# https://drive.google.com/file/d/1ufuVj8U1yfKZrj7qDyjvfwYODF4VshVK/view?usp=sharing
fileDownloaded = drive.CreateFile({'id':'1ufuVj8U1yfKZrj7qDyjvfwYODF4VshVK'})
fileDownloaded.GetContentFile('accessibility_enriched.csv')

accessibility_enriched = pd.read_csv('accessibility_enriched.csv', delimiter=',', encoding='utf-8', low_memory=False, na_values='NaN')

# import to db
engine = create_engine("mysql+pymysql://admin:cse6242110@cse6242.czj7hqwhnoml.us-east-1.rds.amazonaws.com/realestate", echo=True)
accessibility_enriched.to_sql('accessibility_enriched', con=engine, if_exists='replace', index = False, chunksize = 10000)

In [ ]:
## ZIPCODE LEVEL LISTING DATA

# https://drive.google.com/file/d/1337tGOdZ_OPyEpRGJvY31P9GO-uc4jx_/view?usp=sharing
fileDownloaded = drive.CreateFile({'id':'1337tGOdZ_OPyEpRGJvY31P9GO-uc4jx_'})
fileDownloaded.GetContentFile('zipcode_level_listing_detail.csv')

zipcode_level_listing_detail = pd.read_csv('zipcode_level_listing_detail.csv', delimiter=',', encoding='utf-8', low_memory=False, na_values='NaN')

# import to db
engine = create_engine("mysql+pymysql://admin:cse6242110@cse6242.czj7hqwhnoml.us-east-1.rds.amazonaws.com/realestate", echo=True)
zipcode_level_listing_detail.to_sql('zipcode_level_listing_detail', con=engine, if_exists='replace', index = False, chunksize = 10000)

In [ ]:
## FINAL MASTER LISTINGS TABLE

# https://drive.google.com/file/d/1ZZkyb2ZvK_g7N9NzFM3lYsnCRxHDWJq3/view?usp=sharing
fileDownloaded = drive.CreateFile({'id':'1ZZkyb2ZvK_g7N9NzFM3lYsnCRxHDWJq3'})
fileDownloaded.GetContentFile('listings_enriched_model.csv')

listings_enriched_final = pd.read_csv('listings_enriched_model.csv', delimiter=',', encoding='utf-8', low_memory=False, na_values='NaN')

# import to db
engine = create_engine("mysql+pymysql://admin:cse6242110@cse6242.czj7hqwhnoml.us-east-1.rds.amazonaws.com/realestate", echo=True)
listings_enriched_final.to_sql('listings_enriched_final', con=engine, if_exists='replace', index = False, chunksize = 10000)

In [ ]:
## PREDICTED OUTPUT - CBSA Files

# https://drive.google.com/file/d/1arcjtQE0KI7rvB5EQipZqmunarHN0XIh/view?usp=sharing
fileDownloaded = drive.CreateFile({'id':'1arcjtQE0KI7rvB5EQipZqmunarHN0XIh'})
fileDownloaded.GetContentFile('cbsa_file_paths.csv')
cbsa_file_paths = pd.read_csv('cbsa_file_paths.csv', delimiter=',', encoding='utf-8', low_memory=False, na_values='NaN')

engine = create_engine("mysql+pymysql://admin:cse6242110@cse6242.czj7hqwhnoml.us-east-1.rds.amazonaws.com/realestate", echo=True)

for index, row in cbsa_file_paths.iterrows():

  print(str(row['cbsa']), row['file_link'], row['path'])

  # read file from gdrive
  fileDownloaded = drive.CreateFile({'id':row['path']})
  fileDownloaded.GetContentFile('predicted_output_'+str(row['cbsa'])+'.csv')
  output = pd.read_csv('predicted_output_'+str(row['cbsa'])+'.csv', delimiter=',', encoding='utf-8', low_memory=False, na_values='NaN')
  output = output.iloc[:,0:14]
  
  # import to db
  output.to_sql('predicted_output_'+str(row['cbsa']), con=engine, if_exists='replace', index = False, chunksize = 10000)

In [ ]:
## Mapping Tables

# https://drive.google.com/file/d/1_Dz2BCx8rjxLAxqPpbirBGAccYkJYP00/view?usp=sharing
fileDownloaded = drive.CreateFile({'id':'1_Dz2BCx8rjxLAxqPpbirBGAccYkJYP00'})
fileDownloaded.GetContentFile('mapping.csv')

mapping = pd.read_csv('mapping.csv', delimiter=',', encoding='utf-8', low_memory=False, na_values='NaN')

# import to db
engine = create_engine("mysql+pymysql://admin:cse6242110@cse6242.czj7hqwhnoml.us-east-1.rds.amazonaws.com/realestate", echo=True)
mapping.to_sql('mapping', con=engine, if_exists='replace', index = False, chunksize = 10000)

# https://drive.google.com/file/d/1LlDqegwYO9YAWDkCZQGk19gLB7lIO4or/view?usp=sharing
fileDownloaded = drive.CreateFile({'id':'1LlDqegwYO9YAWDkCZQGk19gLB7lIO4or'})
fileDownloaded.GetContentFile('mapping_price.csv')

mapping_price = pd.read_csv('mapping_price.csv', delimiter=',', encoding='utf-8', low_memory=False, na_values='NaN')

# import to db
engine = create_engine("mysql+pymysql://admin:cse6242110@cse6242.czj7hqwhnoml.us-east-1.rds.amazonaws.com/realestate", echo=True)
mapping_price.to_sql('mapping_price', con=engine, if_exists='replace', index = False, chunksize = 10000)

# https://drive.google.com/file/d/1ldobZibYHOCpLDYYS7Vuw2DCHSsZxO3H/view?usp=sharing
fileDownloaded = drive.CreateFile({'id':'1ldobZibYHOCpLDYYS7Vuw2DCHSsZxO3H'})
fileDownloaded.GetContentFile('mapping_age.csv')

mapping_age = pd.read_csv('mapping_age.csv', delimiter=',', encoding='utf-8', low_memory=False, na_values='NaN')

# import to db
engine = create_engine("mysql+pymysql://admin:cse6242110@cse6242.czj7hqwhnoml.us-east-1.rds.amazonaws.com/realestate", echo=True)
mapping_age.to_sql('mapping_age', con=engine, if_exists='replace', index = False, chunksize = 10000)

In [38]:
def data_read(query):
      conn = pymysql.connect(host='cse6242.czj7hqwhnoml.us-east-1.rds.amazonaws.com', user="admin",
                                              password="cse6242110", port=3306, database="realestate"
                                              )
      df = pd.read_sql(query, conn)
      conn.close()
      return df

In [39]:
data_read("SELECT table_name FROM information_schema.tables WHERE table_schema = 'realestate';")

                           TABLE_NAME
0                       accessibility
1              accessibility_enriched
2                        census_final
3                   census_final_2020
4                             listing
5                       listing_price
6             listings_enriched_final
7                             mapping
8                         mapping_age
9                       mapping_price
10             predicted_output_12060
11             predicted_output_12260
12             predicted_output_12580
13             predicted_output_15680
14             predicted_output_16700
15             predicted_output_16740
16             predicted_output_16820
17             predicted_output_17900
18             predicted_output_19660
19             predicted_output_20500
20             predicted_output_22180
21             predicted_output_23580
22             predicted_output_24860
23             predicted_output_25860
24             predicted_output_25940
25             predicted_output_29460
26             predicted_output_34820
27             predicted_output_36100
28             predicted_output_36740
29             predicted_output_37340
30             predicted_output_39580
31             predicted_output_40060
32             predicted_output_43900
33             predicted_output_45300
34             predicted_output_45540
35             predicted_output_47900
36             predicted_output_48900
37                       price_census
38  price_change_by_zipcode_and_month
39                      yelp_enriched
40                            yelp_zc
41                         zip_county
42       zipcode_level_listing_detail

In [41]:
data_read("SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = N'census_final';")

,TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME,ORDINAL_POSITION,COLUMN_DEFAULT,IS_NULLABLE,DATA_TYPE,CHARACTER_MAXIMUM_LENGTH,CHARACTER_OCTET_LENGTH,NUMERIC_PRECISION,NUMERIC_SCALE,DATETIME_PRECISION,CHARACTER_SET_NAME,COLLATION_NAME,COLUMN_TYPE,COLUMN_KEY,EXTRA,PRIVILEGES,COLUMN_COMMENT,GENERATION_EXPRESSION,SRS_ID
0,def,realestate,census_final,cbsa,2,None,YES,bigint,NaN,NaN,19.0,0.0,None,None,None,bigint,,,"select,insert,update,references",,,None
1,def,realestate,census_final,majority_age_group_final,14,None,YES,text,65535.0,65535.0,NaN,NaN,None,utf8mb4,utf8mb4_0900_ai_ci,text,,,"select,insert,update,references",,,None
2,def,realestate,census_final,majority_education_final,17,None,YES,text,65535.0,65535.0,NaN,NaN,None,utf8mb4,utf8mb4_0900_ai_ci,text,,,"select,insert,update,references",,,None
3,def,realestate,census_final,majority_income_final,16,None,YES,text,65535.0,65535.0,NaN,NaN,None,utf8mb4,utf8mb4_0900_ai_ci,text,,,"select,insert,update,references",,,None
4,def,realestate,census_final,majority_industry_final,15,None,YES,text,65535.0,65535.0,NaN,NaN,None,utf8mb4,utf8mb4_0900_ai_ci,text,,,"select,insert,update,references",,,None
5,def,realestate,census_final,mean_household_income_dollars_final,10,None,YES,double,NaN,NaN,22.0,NaN,None,None,None,double,,,"select,insert,update,references",,,None
6,def,realestate,census_final,mean_travel_time_to_work_minutes_final,9,None,YES,bigint,NaN,NaN,19.0,0.0,None,None,None,bigint,,,"select,insert,update,references",,,None
7,def,realestate,census_final,median_age_final,13,None,YES,bigint,NaN,NaN,19.0,0.0,None,None,None,bigint,,,"select,insert,update,references",,,None
8,def,realestate,census_final,percent_family_households_final,12,None,YES,double,NaN,NaN,22.0,NaN,None,None,None,double,,,"select,insert,update,references",,,None
9,def,realestate,census_final,percent_female_final,5,None,YES,double,NaN,NaN,22.0,NaN,None,None,None,double,,,"select,insert,update,references",,,None
10,def,realestate,census_final,percent_male_final,4,None,YES,double,NaN,NaN,22.0,NaN,None,None,None,double,,,"select,insert,update,references",,,None
11,def,realestate,census_final,percent_population_19_under_final,7,None,YES,double,NaN,NaN,22.0,NaN,None,None,None,double,,,"select,insert,update,references",,,None
12,def,realestate,census_final,percent_population_work_from_home_final,11,None,YES,double,NaN,NaN,22.0,NaN,None,None,None,double,,,"select,insert,update,references",,,None
13,def,realestate,census_final,total_population_final,6,None,YES,double,NaN,NaN,22.0,NaN,None,None,None,double,,,"select,insert,update,references",,,None
14,def,realestate,census_final,unemployment_rate_final,8,None,YES,double,NaN,NaN,22.0,NaN,None,None,None,double,,,"select,insert,update,references",,,None
15,def,realestate,census_final,years,3,None,YES,bigint,NaN,NaN,19.0,0.0,None,None,None,bigint,,,"select,insert,update,references",,,None
16,def,realestate,census_final,zipcode,1,None,YES,bigint,NaN,NaN,19.0,0.0,None,None,None,bigint,,,"select,insert,update,references",,,None